version: "3.5"

services:
  database_regular:
    image: mysql:8.0.30
    cpus: 2
    container_name: "database_regular"
    ports:
      - 3310:3306
    environment:
      - MYSQL_ROOT_PASSWORD=regular
      - MYSQL_USER=regular_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=regularpw
    networks:
      - mynetwork
  database_master:
    image: mysql:8.0.30
    cpus: 2
    container_name: "database_master"
    restart: unless-stopped
    ports:
      - 3308:3306
    volumes:
      - mysqldata_master:/var/lib/mysql
      - ./master.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork

  database_slave:
    image: mysql:8.0.30
    cpus: 2
    container_name: "database_slave"
    restart: unless-stopped
    depends_on:
      - database_master
    ports:
      - 3309:3306
    volumes:
      - mysqldata_slave:/var/lib/mysql
      - ./slave.cnf:/etc/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_USER=my_db_user
      - MYSQL_DATABASE=my_db
      - MYSQL_PASSWORD=S3cret
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  mysqldata_master:
  mysqldata_slave:
  mysqldata_regular:
